/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyButton {
        "buttonName": string;
    }
    interface MyHeader {
        "headerTitle": string;
        "imageUrl": string;
    }
    interface MyModal {
        "closeByClickingOutside": boolean;
        "showCloseBtn": boolean;
    }
    interface MyOptions {
        "options": string;
    }
}
declare global {
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    interface HTMLMyHeaderElement extends Components.MyHeader, HTMLStencilElement {
    }
    var HTMLMyHeaderElement: {
        prototype: HTMLMyHeaderElement;
        new (): HTMLMyHeaderElement;
    };
    interface HTMLMyModalElement extends Components.MyModal, HTMLStencilElement {
    }
    var HTMLMyModalElement: {
        prototype: HTMLMyModalElement;
        new (): HTMLMyModalElement;
    };
    interface HTMLMyOptionsElement extends Components.MyOptions, HTMLStencilElement {
    }
    var HTMLMyOptionsElement: {
        prototype: HTMLMyOptionsElement;
        new (): HTMLMyOptionsElement;
    };
    interface HTMLElementTagNameMap {
        "my-button": HTMLMyButtonElement;
        "my-header": HTMLMyHeaderElement;
        "my-modal": HTMLMyModalElement;
        "my-options": HTMLMyOptionsElement;
    }
}
declare namespace LocalJSX {
    interface MyButton {
        "buttonName"?: string;
    }
    interface MyHeader {
        "headerTitle"?: string;
        "imageUrl"?: string;
    }
    interface MyModal {
        "closeByClickingOutside"?: boolean;
        "showCloseBtn"?: boolean;
    }
    interface MyOptions {
        "options"?: string;
    }
    interface IntrinsicElements {
        "my-button": MyButton;
        "my-header": MyHeader;
        "my-modal": MyModal;
        "my-options": MyOptions;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-button": LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
            "my-header": LocalJSX.MyHeader & JSXBase.HTMLAttributes<HTMLMyHeaderElement>;
            "my-modal": LocalJSX.MyModal & JSXBase.HTMLAttributes<HTMLMyModalElement>;
            "my-options": LocalJSX.MyOptions & JSXBase.HTMLAttributes<HTMLMyOptionsElement>;
        }
    }
}
